return {
  MatchParen = { underline = true },
  VertSplit = { fg = C.selection },
  CursorLineNr = { fg = C.bright_purple, bold = true },
  Normal = { bg = C.bg, fg = C.fg },
  NormalFloat = { link = "Normal" },
  Comment = { fg = C.comment, italic = true },
  Constant = { fg = C.bright_cyan },
  String = { fg = C.yellow },
  Character = { fg = C.green },
  Number = { fg = C.purple },
  Boolean = { fg = C.orange },
  Float = { fg = C.orange },
  FloatBorder = { fg = C.grey },
  Operator = { fg = C.purple },
  Keyword = { fg = C.pink, bold = true },
  Keywords = { fg = C.pink, bold = true },
  Identifier = { fg = C.cyan },
  Function = { fg = C.green, bold = true, italic = true },
  Statement = { fg = C.purple },
  Conditional = { fg = C.pink, bold = true, italic = true },
  Repeat = { fg = C.pink, bold = true, italic = true },
  Label = { fg = C.cyan },
  Exception = { fg = C.purple },
  PreProc = { fg = C.yellow },
  Include = { fg = C.bright_purple, bold = true, italic = true },
  Define = { fg = C.purple },
  Title = { fg = C.cyan },
  Macro = { fg = C.purple },
  PreCondit = { fg = C.cyan },
  Type = { fg = C.cyan },
  StorageClass = { fg = C.pink },
  Structure = { fg = C.yellow },
  TypeDef = { fg = C.green },
  Special = { fg = C.green, italic = true },
  SpecialComment = { fg = C.comment, italic = true },
  Error = { fg = C.bright_red },
  Todo = { fg = C.purple, bold = true, italic = true },
  Underlined = { underline = true },
  Cursor = { fg = C.none },
  CursorColumn = { fg = C.none },
  Conceal = { fg = C.comment },
  ColorColumn = { fg = C.none, bg = C.selection },
  CursorLine = { fg = C.none, bg = C.selection },
  Directory = { fg = C.cyan },
  DiffAdd = { fg = C.bg, bg = C.green },
  DiffChange = { fg = C.bright_orange },
  DiffDelete = { fg = C.red, bg = C.red },
  DiffText = { fg = C.comment, bg = C.yellow },
  ErrorMsg = { fg = C.bright_red },
  Folded = { fg = C.comment },
  FoldColumn = { fg = C.none },
  IncSearch = { fg = C.bg, bg = C.bright_yellow },
  LineNr = { fg = C.comment },
  NonText = { fg = C.nontext },
  Pmenu = { fg = C.grey, bg = C.menu },
  PmenuSel = { fg = C.grey, bg = C.selection },
  PmenuSbar = { fg = C.dim_purple, bg = C.visual },
  PmenuThumb = { fg = C.none, bg = C.selection },
  Question = { fg = C.purple },
  QuickFixLine = { fg = C.black, bg = C.yellow },
  Search = { fg = C.comment, bg = C.yellow },
  SignColumn = { fg = C.none },
  SpecialKey = { fg = C.comment },
  SpellBad = { undercurl = true, sp = C.bright_red },
  SpellCap = { undercurl = true, sp = C.bright_yellow },
  SpellLocal = { undercurl = true, sp = C.bright_green },
  SpellRare = { fg = C.yellow },
  StatusLine = { fg = C.fg, bg = C.black },
  StatusLineNC = { fg = C.comment },
  StatusLineTerm = { fg = C.fg, bg = C.black },
  StatusLineTermNC = { fg = C.comment },
  TabLine = { fg = C.comment },
  TabLineSel = { fg = C.grey },
  TabLineFill = { fg = C.none, bg = C.bg },
  Terminal = { fg = C.grey, bg = C.black },
  Visual = { fg = C.none, bg = C.visual },
  VisualNOS = { fg = C.visual },
  WarningMsg = { fg = C.yellow },
  WildMenu = { fg = C.black, bg = C.grey },
  EndOfBuffer = { fg = C.bg },
}
