return {
  cssClassName = { fg = C.bright_green, italic = true },
  cssClassNameDot = { fg = C.bright_green, italic = true },
  cssIdentifier = { fg = C.bright_green, italic = true },
  cssKeyFrameProp = { fg = C.bright_magenta, italic = true },
  cssFunction = { fg = C.bright_magenta },
  cssProp = { fg = C.bright_magenta },
  cssColor = { fg = C.fg },
  cssFunctionName = { fg = C.green, bold = true },
  cssAtRule = { fg = C.purple, bold = true },
  cssImportant = { fg = C.bright_orange, bold = true },
  cssTagName = { fg = C.cyan, bold = true, italic = true },
  cssAttr = { fg = C.fg },
  cssBraces = { fg = C.none, bg = C.none, bold = true },
}
