return {
  cssClassName = { fg = C.bright_cyan, italic = true },
  cssClassNameDot = { fg = C.bright_cyan, italic = true },
  cssIdentifier = { fg = C.bright_cyan, italic = true },
  cssKeyFrameProp = { fg = C.pink, italic = true, bold = true },
  cssFunction = { fg = C.bright_magenta },
  cssProp = { fg = C.bright_purple },
  cssColor = { fg = C.fg },
  cssFunctionName = { fg = C.green, bold = true },
  cssAtRule = { fg = C.pink, bold = true },
  cssImportant = { fg = C.pink, bold = true },
  cssTagName = { fg = C.cyan, bold = true, italic = true },
  cssAttr = { fg = C.fg },
  cssBraces = { fg = C.none, bg = C.none, bold = true },
  cssCommonAttr = { fg = C.bright_magenta },
}
