return {
  DiagnosticVirtualTextError = { italic = true, fg = C.dim_red },
  DiagnosticVirtualTextHint = { italic = true, fg = C.dim_cyan },
  DiagnosticVirtualTextWarn = { italic = true, fg = C.dim_orange },
  DiagnosticVirtualTextInfo = { italic = true, fg = C.dim_green },
  DiagnosticError = { fg = C.dim_red },
  DiagnosticWarn = { fg = C.dim_yellow },
  DiagnosticInfo = { fg = C.dim_cyan },
  DiagnosticHint = { fg = C.dim_cyan },
  DiagnosticUnderlineError = { sp = C.dim_red, undercurl = true },
  DiagnosticUnderlineWarn = { sp = C.dim_yellow, undercurl = true },
  DiagnosticUnderlineInfo = { sp = C.dim_cyan, undercurl = true },
  DiagnosticUnderlineHint = { sp = C.dim_cyan, undercurl = true },
  DiagnosticSignError = { fg = C.dim_red },
  DiagnosticSignWarn = { fg = C.dim_yellow },
  DiagnosticSignInfo = { fg = C.dim_cyan },
  DiagnosticSignHint = { fg = C.dim_cyan },
  DiagnosticFloatingError = { fg = C.dim_red },
  DiagnosticFloatingWarn = { fg = C.dim_yellow },
  DiagnosticFloatingInfo = { fg = C.dim_cyan },
  DiagnosticFloatingHint = { fg = C.dim_cyan },
}
