return {
  LspReferenceWrite = { bg = C.selection },
  LspReferenceRead = { bg = C.selection },
  LspReferenceText = { bg = C.selection },
  LspDiagnosticsDefaultError = { fg = C.red },
  LspDiagnosticsDefaultWarning = { fg = C.yellow },
  LspDiagnosticsDefaultInformation = { fg = C.cyan },
  LspDiagnosticsDefaultHint = { fg = C.cyan },
  LspDiagnosticsUnderlineError = { fg = C.red, undercurl = true },
  LspDiagnosticsUnderlineWarning = { fg = C.yellow, undercurl = true },
  LspDiagnosticsUnderlineInformation = { fg = C.cyan, undercurl = true },
  LspDiagnosticsUnderlineHint = { fg = C.cyan, undercurl = true },
  LspSagaDiagnosticBorder = { fg = C.fg },
  LspSagaSignatureHelpBorder = { fg = C.fg },
  LspSagaLspFinderBorder = { fg = C.fg },
  LspSagaCodeActionBorder = { fg = C.fg },
  LspSagaDefPreviewBorder = { fg = C.fg },
  LspSagaHoverBorder = { fg = C.fg },
  LspSagaRenameBorder = { fg = C.fg },
  LspSagaRenamePromptPrefix = { fg = C.fg },
  LspFloatWinBorder = { fg = C.fg },
  LspSagaDiagnosticTruncateLine = { fg = C.fg },
  LspSagaShTruncateLine = { fg = C.fg },
  LspSagaDocTruncateLine = { fg = C.fg },
  LspSagaCodeActionTruncateLine = { fg = C.fg },
  ProviderTruncateLine = { fg = C.fg },
  DiagnosticTruncateLine = { fg = C.fg, bold = true },
  LspSagaCodeActionTitle = { fg = C.yellow, bold = true },
  LspSagaCodeActionContent = { fg = C.green, bold = true },
  LspFloatWinNormal = { fg = C.fg, bg = C.black },
  LspDiagnosticsFloatingError = { fg = C.red },
  LspDiagnosticsFloatingWarn = { fg = C.orange },
  LspDiagnosticsFloatingInfor = { fg = C.white },
  LspDiagnosticsFloatingHint = { fg = C.yellow },
  LspSagaDiagnosticHeader = { fg = C.yellow },
  LspSagaBorderTitle = { fg = C.yellow, bold = true },
  DiagnosticInformation = { fg = C.yellow, bold = true },
}
