return {
  BufferLineIndicatorSelected = { fg = C.bright_purple, bg = C.bg },
  BufferLineFill = { bg = C.selection },
  BufferLineBufferSelected = { fg = C.bright_purple, bg = C.bg, bold = true },
  BufferLineBackground = { bg = C.visual, fg = C.dim_purple },
  BufferLineSeparator = { bg = C.visual, fg = C.visual },
  BufferLineSeparatorSelected = { bg = C.bg, fg = C.bg },
  BufferLineCloseButton = { bg = C.visual },
  BufferLineModified = { bg = C.visual },
  BufferLineBufferVisible = { fg = C.fg, bg = C.bg },
  BufferLineTab = { fg = C.fg, bg = C.bg },
  BufferLineTabSelected = { fg = C.bg, bg = C.bg },
  BufferLineTabClose = { fg = C.bg, bg = C.bg },
  BufferLineSeparatorVisible = { fg = C.bg, bg = C.bg },
  BufferLineCloseButtonVisible = { fg = C.red, bg = C.bg },
  BufferLineCloseButtonSelected = { fg = C.red, bg = C.bg },
  BufferLineModifiedVisible = { fg = C.fg, bg = C.bg },
  BufferLineModifiedSelected = { fg = C.yellow, bg = C.bg },
  BufferLineError = { fg = C.bright_red, bg = C.red },
  BufferLineErrorDiagnostic = { fg = C.bright_red, bg = C.red_1 },
  BufferLineDuplicate = { fg = C.comment, bg = C.visual },
}
