return {
  NvimTreeFolderIcon = { fg = C.bright_purple },
  NvimTreeExecFile = { fg = C.green },
  NvimTreeOpenedFile = { fg = C.cyan },
  NvimTreeRootFolder = { fg = C.purple, bold = true },
  NvimTreeEndOfBuffer = { fg = C.bg },
  NvimTreeNormal = { link = "Normal" },
  NvimTreeNormalNC = { link = "Normal" },
  NvimTreeVertSplit = { link = "VertSplit" },
  NvimTreeImageFile = { fg = C.purple },
  NvimTreeSymlink = { fg = C.cyan },
  NvimTreeSpecialFile = { fg = C.bright_magenta },
  NvimTreeGitDeleted = { fg = C.bright_red },
  NvimTreeGitMerge = { fg = C.bright_orange },
  NvimTreeGitRenamed = { fg = C.yellow },
  NvimTreeGitStaged = { fg = C.green },
  NvimTreeGitDirty = { fg = C.red },
  NvimTreeGitNew = { fg = C.green },
}
