return {
  TelescopeNormal = { fg = C.fg, bg = C.menu },
  TelescopeTitle = { fg = C.fg },
  TelescopeBorder = { fg = C.menu, bg = C.menu },
  TelescopeMatching = { fg = C.cyan },
  TelescopeSelection = { bg = C.selection },
  TelescopeSelectionCaret = { fg = C.purple, bg = C.selection },
  TelescopeMultiIcon = { fg = C.cyan },
  TelescopeMultiSelection = { fg = C.cyan },
  TelescopePromptTitle = { fg = C.menu, bg = C.red },
  TelescopePromptNormal = { fg = C.fg, bg = C.menu },
  TelescopePromptPrefix = { fg = C.red, bg = C.menu },
  TelescopePromptCounter = { fg = C.dim_purple },
  TelescopeResultsTitle = { fg = C.menu, bg = C.cyan },
  TelescopeResultsNormal = { fg = C.fg, bg = C.menu },
  TelescopePreviewTitle = { fg = C.menu, bg = C.green },
  TelescopePreviewNormal = { fg = C.fg, bg = C.menu },
}
