return {
  TelescopeNormal = { fg = C.fg, bg = C.menu },
  TelescopeTitle = { fg = C.fg },
  TelescopeBorder = { fg = C.menu, bg = C.menu },
  TelescopeMatching = { fg = C.cyan },
  -- TelescopeSelection = { bg = C.selection },
  -- TelescopeSelectionCaret = { fg = C.purple, bg = C.selection },
  -- TelescopeMultiIcon = { fg = C.cyan },
  -- TelescopeMultiSelection = { fg = C.cyan },
  TelescopePromptTitle = { fg = C.menu, bg = C.red },
  TelescopePromptNormal = { fg = C.fg, bg = C.menu },
  TelescopePromptPrefix = { fg = C.red, bg = C.menu },
  -- TelescopePromptCounter = { fg = C.fg },
  -- TelescopePromptBorder = { fg = C.menu, bg = C.menu },
  TelescopeResultsTitle = { fg = C.menu, bg = C.menu },
  TelescopeResultsNormal = { fg = C.fg, bg = C.menu },
  -- TelescopeResultsBorder = { fg = C.comment },
  TelescopePreviewTitle = { fg = C.menu, bg = C.green },
  -- TelescopePreviewBorder = { fg = C.comment },
  TelescopePreviewNormal = { fg = C.fg, bg = C.menu },
}
